package com.example.java_final_assignment.controllers;

import com.example.java_final_assignment.GlobalResponse.AppResponse;
import com.example.java_final_assignment.controllers.requests.LoginRequestDTO;
import com.example.java_final_assignment.controllers.requests.RegisterRequestDTO;
import com.example.java_final_assignment.service.AuthService;
import lombok.AllArgsConstructor;
import org.springframework.web.bind.annotation.*;

//instead of returning Generic AppResponse, you may return a specific DTO

@RestController
@RequestMapping("/auth")
@AllArgsConstructor
public class AuthController {

    private final AuthService authService;

    @GetMapping("/hello")
    public String hello(){
        return "Hello Springboot";
    }

    
    //this should be protected by ADMIN role 
    //ADMIN user should be generated by application on startup (see liquibase migration)
    //you can move it to UserController
    @PostMapping("/register")
    public AppResponse register(
            @RequestBody RegisterRequestDTO request
    ) {
      return authService.registerUser(request);
    }

    //there should be admin user present in DB by app (you may add liquibase migration for thsi purpose)
    //currently, I cannot create ADMIN user
    @PostMapping("/login")
    public AppResponse login(@RequestBody LoginRequestDTO request){
        return authService.login(request);
    }
}
