server:
  port: 5101

spring:
  application:
    name: java-final-assignment
  datasource:
    url: jdbc:postgresql://localhost:5435/task_management
    username: postgres
    password: 05xJunaid

  jpa:
    hibernate:
      # Because Liquibase will manage schema.
      ddl-auto: validate
    properties:
      hibernate:
        # Makes long SQL queries readable in logs.
        format_sql: true
        # Highlights SQL keywords in console color.
        highlight_sql: true
    show-sql: false
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    'org.springframework.transaction': DEBUG
    'org.springframework.transaction.interceptor': TRACE
    'org.springframework.orm.jpa': DEBUG
    'org.hibernate': DEBUG
    'org.hibernate.SQL': DEBUG
    'org.hibernate.orm.jdbc.bind': TRACE
    'org.hibernate.orm.jdbc.extract': TRACE
    'org.hibernate.event.internal': TRACE
    'org.hibernate.engine.internal': TRACE
    'org.hibernate.engine.spi.ActionQueue': TRACE
    'org.hibernate.internal.SessionImpl': TRACE
    'org.hibernate.internal.SessionFactoryImpl': DEBUG
    'org.hibernate.resource.jdbc': TRACE
    'org.hibernate.stat': DEBUG
    'org.springframework.web': INFO
  pattern:
    # Explicitly including the [TraceID: %X{traceId}] variable in the output structure
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level - [TraceID: %X{traceId}] %logger{36} - %msg%n"
